### ISSUE TITLE
是无web界面吗？

### ISSUE THREAD

**Issue by zhucaidan** [ellermister/shorturl#2]
上传php后访问网页是空白的
请问下是无web界面吗？
还是对环境有要求，使用的是php7.4

**Comment by ellermister** [comment]
需要你把 view 也clone下来才有界面。

**Comment by zhucaidan** [comment]
有的，我是直接download ZIP
环境是用宝塔搭建的，PHP我试过5.6 7.1 7.4都不行，打开后就是空白
![QQ截图20201106184153](https://user-images.githubusercontent.com/47970938/98430088-f89db880-205f-11eb-89cb-c2b30445421d.png)

**Comment by rrrzr** [comment]
我和楼上的问题一样，宝塔搭建的打开也是空白

**Comment by Jacky-Bruse** [comment]
我也是，请问解决没？

**Comment by 1047730442** [comment]
无解？？？

**Comment by aipap** [comment]
貌似无解，只不过挂后台，执行bash 命令行的，会有返回值。不过也全部是127.0.0.1的，并不能用到实际当中来

**Comment by aipap** [comment]
可以用的，完美解决。多去研究吧

**Comment by zhucaidan** [comment]
> 可以用的，完美解决。多去研究吧

宝塔怎么配置呢？是有php参数被禁止了么

**Comment by aipap** [comment]
Path-info ng要配置好

**Comment by aipap** [comment]
现在基本都是能用的了，不过，加密跳转和伪装页面 不能同时开起来，演示站倒是可以。 伪静态方便给出来下吗？谢谢。
