### ISSUE TITLE
宝塔环境下打开为空白，缺少PHP拓展或者函数？

### ISSUE THREAD

**Issue by zhucaidan** [ellermister/shorturl#3]
宝塔环境下下载全部源码部署后打开为空白，是否是因为缺少PHP拓展？或者某些函数被禁用？
环境为：Nginx 1.18.0；PHP7.3；已开启的拓展和禁用的函数如下图：
![1](https://user-images.githubusercontent.com/47970938/100497484-b6244480-3110-11eb-94ad-15a63ee80954.png)
![2](https://user-images.githubusercontent.com/47970938/100497487-b9b7cb80-3110-11eb-97c9-566625e8128b.png)
![3](https://user-images.githubusercontent.com/47970938/100497490-bc1a2580-3110-11eb-8e91-4124b43889a9.png)
![4](https://user-images.githubusercontent.com/47970938/100497493-bde3e900-3110-11eb-833f-a8f7427d85f1.png)
![5](https://user-images.githubusercontent.com/47970938/100497496-c0ded980-3110-11eb-88e0-fdf09f31456a.png)
![6](https://user-images.githubusercontent.com/47970938/100497498-c3413380-3110-11eb-9a3f-6c35d4c9f371.png)
![7](https://user-images.githubusercontent.com/47970938/100497501-c5a38d80-3110-11eb-9a30-ccbcbebe22eb.png)
![8](https://user-images.githubusercontent.com/47970938/100497503-c76d5100-3110-11eb-81b4-2cc490907a71.png)

**Comment by Jacky-Bruse** [comment]
解决了吗？请问，我也是同样情况

**Comment by zhucaidan** [comment]
> 解决了吗？请问，我也是同样情况

没有。。作者貌似不回issue

**Comment by Jacky-Bruse** [comment]
> > 解决了吗？请问，我也是同样情况
> 
> 没有。。作者貌似不回issue
好的，谢谢，我找其它源码试试

**Comment by aipap** [comment]
一个样子，默认打开是一片空白。难道是路由没有做好吗？
